"""
CrewAI Tool: Sends the executive optimization action plan email with 1-Click Approve/Reject links.
"""
from __future__ import annotations

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class SendEmailInput(BaseModel):
    proposal_id: str = Field(..., description="The staged proposal_id generated by the staging tool.")
    executive_summary: str = Field(..., description="A concise 3-4 bullet point summary of system health, tokens, cost, and feedback.")
    action_plan: str = Field(..., description="The exact concrete actions proposed (target template, prompt edits, model selection).")


class SendOptimizationEmailTool(BaseTool):
    name: str = "Send Optimization Action Plan Email"
    description: str = (
        "Sends an executive summary email containing the optimization action plan and "
        "one-click Approve and Reject links directly to the administrator."
    )
    args_schema: Type[BaseModel] = SendEmailInput

    def _run(self, proposal_id: str, executive_summary: str, action_plan: str) -> str:
        smtp_host = os.getenv("SMTP_HOST")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USER")
        smtp_password = os.getenv("SMTP_PASSWORD_AGENTIC")
        approver_email = os.getenv("APPROVER_EMAIL")
        base_url = os.getenv("APPROVAL_BASE_URL", "http://localhost:8001")

        if not all([smtp_host, smtp_user, smtp_password, approver_email]):
            return "Error: SMTP email configuration is missing in environment variables."

        approve_url = f"{base_url}/optimization/approve?proposal_id={proposal_id}&decision=approve"
        reject_url = f"{base_url}/optimization/approve?proposal_id={proposal_id}&decision=reject"

        # Plaintext Body
        text_body = (
            f"=== 🤖 HOURLY SYSTEM OPTIMIZATION REPORT ===\n\n"
            f"Proposal ID: {proposal_id}\n\n"
            f"📊 EXECUTIVE SUMMARY:\n{executive_summary}\n\n"
            f"🎯 PROPOSED ACTION PLAN:\n{action_plan}\n\n"
            f"--------------------------------------------------\n"
            f"👉 APPROVE & DEPLOY TO PRODUCTION:\n{approve_url}\n\n"
            f"👉 REJECT PROPOSAL:\n{reject_url}\n"
            f"--------------------------------------------------\n"
        )

        # HTML Body with 1-Click Action Buttons
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
                <h2 style="color: #2b5797;">🤖 Hourly Multi-Agent Optimization Report</h2>
                <p><strong>Proposal ID:</strong> <code>{proposal_id}</code></p>
                <hr style="border: none; border-top: 1px solid #eee;">
                
                <h3>📊 Executive Summary</h3>
                <div style="background-color: #f9f9f9; padding: 12px; border-radius: 6px;">
                    <pre style="white-space: pre-wrap; font-family: inherit; margin: 0;">{executive_summary}</pre>
                </div>

                <h3>🎯 Proposed Action Plan</h3>
                <div style="background-color: #f0f7ff; padding: 12px; border-radius: 6px; border-left: 4px solid #0078d4;">
                    <pre style="white-space: pre-wrap; font-family: inherit; margin: 0;">{action_plan}</pre>
                </div>

                <div style="margin-top: 30px; text-align: center;">
                    <a href="{approve_url}" style="background-color: #107c41; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-right: 15px; display: inline-block;">
                        ✅ Approve & Deploy
                    </a>
                    <a href="{reject_url}" style="background-color: #d83b01; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                        ❌ Reject Proposal
                    </a>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[Action Required] System Optimization Proposal: {proposal_id}"
        msg["From"] = smtp_user
        msg["To"] = approver_email

        msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.starttls()
                server.login(smtp_user, smtp_password)
                server.sendmail(smtp_user, [approver_email], msg.as_string())

            logger.info(f"📧 Optimization proposal email sent successfully to {approver_email} (ID: {proposal_id})")
            return f"Action plan email successfully sent to {approver_email} with Proposal ID '{proposal_id}'."
        except Exception as exc:
            logger.error(f"Failed to send email: {exc}", exc_info=True)
            return f"Error sending email: {exc}"