# ============================================================
# classesForllm.py
# ============================================================
from abc import ABC, abstractmethod
import os
from typing import Literal, Optional
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_core.output_parsers import PydanticOutputParser
from prompt import Prompt
from history import ConversationHistory
import logging
import uuid

logger = logging.getLogger(__name__)

load_dotenv()

# --- Common response contract, independent of which LLM produced it ---
class LLMResponse(BaseModel):
    output: str = Field(
        description="The filtered answer extracted from the retrieved documents, or 'No relevant document found' if the documents don't answer the query"
    )
    isAnswerFound: bool = Field(
        description="True if the retrieved documents contain information relevant to the query, false otherwise"
    )

class LLMResponseLanggraph(BaseModel):
    llm_responseLanggraph: str = Field(
        default="", 
        description="The output response generated by you to the input message of user"
    )
    tool_needed: bool = Field(
        default=False, 
        description="Whether a tool call is needed to answer this user input or not"
    )
    rewrittenQueryforVectorsearch : str = Field(
        default="",
        description=(
            "Convert the user's latest question into a standalone, context-complete, and self-contained search query. "
            "Analyze the conversation history to resolve and replace all pronouns (e.g., 'it', 'its', 'the policy', 'their') "
            "with the explicit policy names, products, or customer entities previously discussed. "
            "Preserve any specific years, numbers, codes, or keywords. "
            "Must be a pure, search-optimized query free of conversational greetings, polite preambles, or explanations."
            )
        )

# --- The contract every LLM backend must satisfy ---
class LLMSelection(ABC):
    @abstractmethod
    async def sendMessagestollm(self, session_id: str, userInput: str) -> LLMResponse:
        """Format (with history), send, parse, and persist the turn — each
        implementation does this its own way."""
        pass

    @abstractmethod
    def structuredllm(self):
        """Return a version of the LLM that produces structured output (e.g., JSON).
        This is used for nodes that require structured responses."""
        pass

    @abstractmethod
    def rawllm(self):
        pass

    @abstractmethod
    async def filteringresultwithLLM(self, parenttext: list[str], query: str) -> LLMResponse:
        pass

    @abstractmethod
    async def close(self) -> None:
        """Release any resources. No-op if the backend has nothing to close."""
        pass


# ============================================================
# Bedrock implementation (native langchain_aws) — owns its own config,
# formatting, parsing
# ============================================================
class ChatBedrockLLM(LLMSelection):

    def __init__(self, prompt_provider: Prompt, history: ConversationHistory):
        from langchain_aws import ChatBedrockConverse

        self._prompt_provider = prompt_provider
        self._history = history
        self._llm = ChatBedrockConverse(
            model_id=os.getenv("MODELID"),
            region_name=os.getenv("REGION"),
            temperature=float(os.getenv("TEMPERATURE", "0.7")),
            max_tokens=int(os.getenv("MAXTOKENS", "1024")),
        )

    async def sendMessagestollm(self, session_id: str, userInput: str) -> LLMResponse:
        messages = self._format_messages(session_id, userInput)
        dynamic_headers = {
            "X-Request-ID": str(uuid.uuid4())
        }
        raw = await self._llm.ainvoke(messages, headers=dynamic_headers)
        logger.info(f"Raw response from Bedrock LLM: {raw}")
        response = self._parse_response(raw)

        self._history.append(session_id, [
            HumanMessage(content=userInput),
            AIMessage(content=response.output),
        ])
        return response.output

    async def filteringresultwithLLM(self, parenttext: list[str], query: str) -> LLMResponse:
        messages = self._format_messagesForFiltering(parenttext, query)
        dynamic_headers = {
            "X-Request-ID": str(uuid.uuid4())
        }
        raw = await self._llm.ainvoke(messages, headers=dynamic_headers)
        response = self._parse_response(raw)
        return response.output

    def _format_messages(self, session_id: str, userInput: str) -> list:
        past = self._history.get(session_id)
        return [
            SystemMessage(content=self._prompt_provider.systemprompt()),
            *past,
            HumanMessage(content=userInput),
        ]

    def _format_messagesForFiltering(self, parenttext: list[str], userInput: str) -> list:
        return [
            SystemMessage(content=self._prompt_provider.filteringsystemprompt(parenttext)),
            HumanMessage(content=userInput),
        ]

    def _parse_response(self, raw) -> LLMResponse:
        return LLMResponse(output=raw.content)

    def rawllm(self):
        return self._llm

    def structuredllm(self):
        return self._llm.with_structured_output(LLMResponseLanggraph, method="json_schema")

    async def close(self) -> None:
        pass


# ============================================================
# NEW: Bedrock via the OpenAI-compatible "mantle" endpoint.
# Not a LangChain chat model, so structured output is enforced manually
# with PydanticOutputParser (format instructions injected into the
# system prompt, response parsed back into a pydantic object).
# ============================================================
class ChatBedrockOpenAILLM(LLMSelection):

    def __init__(self, prompt_provider: Prompt, history: ConversationHistory):
        from langchain_openai import ChatOpenAI

        self._prompt_provider = prompt_provider
        self._history = history
        self._llm = ChatOpenAI(
            model=os.getenv("BEDROCK_MANTLE_MODEL", "deepseek.v3.1"),
            api_key=os.getenv("APIKEYFORBEDROCK"),
            base_url=os.getenv(
                "BEDROCK_MANTLE_BASE_URL",
                "https://bedrock-mantle.ap-south-1.api.aws/v1",
            ),
            default_headers={"OpenAI-Project": "default"},
            timeout = int(os.getenv("TIMEOUT")),
            max_retries = int(os.getenv("MAXRETRIES")),
            temperature = float(os.getenv("TEMPERATURE"))
        )

    async def sendMessagestollm(self, session_id: str, userInput: str) -> LLMResponse:
        messages = self._format_messages(session_id, userInput)
        dynamic_headers = {
            "X-Request-ID": str(uuid.uuid4())
        }
        raw = await self._llm.ainvoke(messages, headers=dynamic_headers)
        logger.info(f"Raw response from Bedrock (mantle) LLM: {raw}")
        response = self._parse_response(raw)

        self._history.append(session_id, [
            HumanMessage(content=userInput),
            AIMessage(content=response.output),
        ])
        return response.output

    async def filteringresultwithLLM(self, parenttext: list[str], query: str) -> LLMResponse:
        messages = self._format_messagesForFiltering(parenttext, query)
        structuredLLM = self._llm.with_structured_output(LLMResponse, method="json_schema")
        
        # Format the config for a Structured LLM sequence run
        config = {
            "headers": {
                "X-Request-ID": str(uuid.uuid4())
            }
        }
        response: LLMResponse = await structuredLLM.ainvoke(messages, config=config)
        return response

    def _format_messages(self, session_id: str, userInput: str) -> list:
        past = self._history.get(session_id)
        return [
            SystemMessage(content=self._prompt_provider.systemprompt()),
            *past,
            HumanMessage(content=userInput),
        ]

    def _format_messagesForFiltering(self, parenttext: list[str], userInput: str) -> list:
        return [
            SystemMessage(content=self._prompt_provider.filteringsystemprompt(parenttext)),
            HumanMessage(content=userInput),
        ]

    def _parse_response(self, raw) -> LLMResponse:
        return LLMResponse(output=raw.content)

    def rawllm(self):
        return self._llm

    def structuredllm(self):
        return self._llm.with_structured_output(LLMResponseLanggraph, method="json_schema")

    async def close(self) -> None:
        pass

# ============================================================
# Example second backend — OpenAI, initialized differently,
# formats/parses differently, but honors the same contract.
# ============================================================
class ChatOpenAILLM(LLMSelection):

    def __init__(self, prompt_provider: Prompt, history: ConversationHistory):
        from langchain_openai import ChatOpenAI

        self._prompt_provider = prompt_provider
        self._history = history
        self._llm = ChatOpenAI(
            model=os.getenv("OPENAI_MODEL"),
            api_key=os.getenv("OPENAI_API_KEY"),
            temperature=float(os.getenv("OPENAI_TEMPERATURE", "0.7")),
        )

    async def sendMessagestollm(self, session_id: str, userInput: str) -> LLMResponse:
        prompt = self._build_prompt(session_id, userInput)
        dynamic_headers = {
            "X-Request-ID": str(uuid.uuid4())
        }
        raw = await self._llm.ainvoke(prompt, headers=dynamic_headers)
        logger.info(f"Raw response from OpenAI LLM: {raw}")
        response = self._parse_response(raw)

        self._history.append(session_id, [
            HumanMessage(content=userInput),
            AIMessage(content=response.output),
        ])
        return response

    def _build_prompt(self, session_id: str, userInput: str) -> str:
        past = self._history.get(session_id)
        history_text = "\n".join(
            f"{'User' if isinstance(m, HumanMessage) else 'Assistant'}: {m.content}"
            for m in past
        )
        return f"{self._prompt_provider.systemprompt()}\n\n{history_text}\n\nUser: {userInput}"

    def _parse_response(self, raw) -> LLMResponse:
        return LLMResponse(output=raw.content)

    def rawllm(self):
        return self._llm
    
    def structuredllm(self):
        return self._llm.with_structured_output(LLMResponseLanggraph)
    
    async def close(self) -> None:
        pass


# ============================================================
# Factory — the only place that knows which concrete class to build (OCP)
# ============================================================
class LLMFactory:
    _registry: dict[str, type[LLMSelection]] = {
        "bedrock": ChatBedrockLLM,
        "bedrock_mantle": ChatBedrockOpenAILLM,
        "openai": ChatOpenAILLM,
    }

    @classmethod
    def create(cls, provider: str, prompt_provider: Prompt, history: ConversationHistory) -> LLMSelection:
        try:
            llm_cls = cls._registry[provider]
        except KeyError:
            raise ValueError(f"Unknown LLM provider: {provider}")
        return llm_cls(prompt_provider=prompt_provider, history=history)

    @classmethod
    def register(cls, name: str, llm_cls: type[LLMSelection]) -> None:
        """Lets new LLMs be plugged in without editing this file (true OCP)."""
        cls._registry[name] = llm_cls